#!/usr/bin/env python3
"""Tuner test kit — a local, stdlib-only IPTV provider for end-to-end testing.

Serves the media generated by ``make_media.sh`` (``TestMedia/`` at the repo root) as

* an extended-M3U playlist + XMLTV guide        ``/playlist.m3u``, ``/epg.xml``, ``/epg.xml.gz``
* an Xtream Codes panel (user ``test`` / ``test``) ``/player_api.php``, ``/get.php``, ``/xmltv.php``,
                                                  ``/live|movie|series|timeshift/...``
* pseudo-live MPEG-TS and live HLS that follow the wall clock: every client joining a channel sees the
  same "broadcast" position, and timestamps / continuity counters are rewritten on every loop of the
  source clip so the stream never jumps backwards.

Usage:  python3 scripts/testkit/server.py [PORT] [--host HOST]
        (or the TESTKIT_PORT / TESTKIT_HOST / TESTKIT_MEDIA environment variables)

The catalog below (FEEDS / MOVIES / SERIES) is also imported by make_media.sh so the titles burned into
the videos always match what the playlists and APIs report.
"""

from __future__ import annotations

import argparse
import base64
import bisect
import datetime as dt
import functools
import gzip
import json
import math
import os
import random
import re
import sys
import threading
import time
import traceback
import urllib.parse
from array import array
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from xml.sax.saxutils import escape

# --------------------------------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parents[2]
MEDIA = Path(os.environ.get("TESTKIT_MEDIA") or (ROOT / "TestMedia")).resolve()
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
CONFIG = {"host": DEFAULT_HOST, "port": DEFAULT_PORT}

USERNAME = "test"
PASSWORD = "test"
LOCKED_UA = "TunerTestKit/1.0 (UA-locked channel)"
LOCKED_UA_TOKEN = "TunerTestKit"          # /ua/ streams require this substring in User-Agent
LOCKED_REFERRER = "http://tuner.test/"    # sent via #EXTVLCOPT:http-referrer, logged (not enforced)

ANCHOR = float(int(time.time()) - 3600)   # virtual broadcast start: the "channels" went on air 1 h ago
LIVE_LEAD = 1.0                           # seconds a pseudo-live TS client may run ahead of the wall clock
HLS_WINDOW = 6                            # segments listed in a live HLS playlist
FLAKY_STALL_AFTER = 20.0                  # /flaky/ streams stop sending (but keep the socket) after this
ARCHIVE_MAX = 3 * 3600                    # longest catchup we synthesise for ?utc= requests

# --------------------------------------------------------------------------------------------------
# Catalog (shared with make_media.sh)
# --------------------------------------------------------------------------------------------------

FEED_SECONDS = 64        # 64 s = 1600 video frames @25 fps = 3000 AAC frames @48 kHz: loops seamlessly
EPISODE_SECONDS = 30

FEEDS = {
    1: {"slug": "news", "name": "Tuner News", "tvg": "news.tuner", "tagline": "NEWS 24/7",
        "color": (32, 96, 220), "tone": 440},
    2: {"slug": "sports", "name": "Tuner Sports", "tvg": "sports.tuner", "tagline": "LIVE SPORTS",
        "color": (30, 160, 80), "tone": 554},
    3: {"slug": "movies", "name": "Tuner Movies", "tvg": "movies.tuner", "tagline": "MOVIES & DRAMA",
        "color": (160, 50, 180), "tone": 659},
    4: {"slug": "kids", "name": "Tuner Kids", "tvg": "kids.tuner", "tagline": "KIDS & FAMILY",
        "color": (240, 140, 20), "tone": 880},
}

MOVIES = [
    {
        "id": 1001, "title": "Big Buck Test", "year": 2021, "ext": "mp4", "category": "10",
        "file": "movies/1001-big-buck-test.mp4", "seconds": 90, "color": (210, 120, 40),
        "rating": "7.4", "genre": "Animation, Comedy", "director": "Rhea Tester",
        "cast": "Bun E. Rabbit, Chinchilla Hall, Frank Flier", "country": "Netherlands",
        "release": "2021-06-18", "trailer": "aqz-KE-bpKQ",
        "plot": "A large, gentle test pattern takes revenge on three rodents who keep dropping frames. "
                "Plain MP4 with +faststart: the baseline VOD playback and seek test.",
        "audio": [("eng", "English", 330, 1)], "subtitles": False,
    },
    {
        "id": 1002, "title": "The Multitrack Mystery", "year": 2023, "ext": "mp4", "category": "11",
        "file": "movies/1002-multitrack-mystery.mp4", "seconds": 90, "color": (60, 70, 170),
        "rating": "6.8", "genre": "Mystery, Thriller", "director": "Alma Track",
        "cast": "Stereo Jones, Mono Martinez, Sub Titlé", "country": "Spain",
        "release": "2023-02-10", "trailer": "",
        "plot": "Two audio tracks, two subtitle tracks, one detective. English audio beeps low once a "
                "second; the Spanish track beeps high twice. Use it to test track switching.",
        "audio": [("eng", "English", 330, 1), ("spa", "Español (commentary)", 990, 2)], "subtitles": True,
    },
    {
        "id": 1003, "title": "Matroska Nights", "year": 2019, "ext": "mkv", "category": "11",
        "file": "movies/1003-matroska-nights.mkv", "seconds": 90, "color": (150, 30, 50),
        "rating": "5.9", "genre": "Drama", "director": "Matt Roska",
        "cast": "Ebml Header, Cluster Block, Cue Point", "country": "Russia",
        "release": "2019-11-02", "trailer": "",
        "plot": "A container drama in Matroska: H.264 + two AAC tracks + SRT subtitles. Plays in mpv; "
                "AVFoundation cannot open MKV, so this checks the engine fallback/error path.",
        "audio": [("eng", "English", 330, 1), ("fre", "Français", 990, 2)], "subtitles": True,
    },
    # Real titles: the Blender Foundation's open movies (CC BY). Online metadata (Cinemeta/TMDB) matches them,
    # so they show logos, backdrops, ratings and cast. The playable file is still a synthetic clip.
    {
        "id": 1004, "title": "Big Buck Bunny", "year": 2008, "ext": "mp4", "category": "13",
        "file": "movies/1004-big-buck-bunny.mp4", "seconds": 60, "color": (90, 150, 60),
        "rating": "6.8", "genre": "Animation, Comedy", "director": "Sacha Goedegebure",
        "cast": "", "country": "Netherlands", "release": "2008-05-30", "trailer": "",
        "plot": "A big, good-natured rabbit gets even with three forest bullies. Blender Foundation open movie (CC BY).",
        "audio": [("eng", "English", 440, 1)], "subtitles": False,
    },
    {
        "id": 1005, "title": "Sintel", "year": 2010, "ext": "mp4", "category": "13",
        "file": "movies/1005-sintel.mp4", "seconds": 60, "color": (170, 70, 40),
        "rating": "7.6", "genre": "Animation, Fantasy", "director": "Colin Levy",
        "cast": "Halina Reijn, Thom Hoffman", "country": "Netherlands", "release": "2010-09-27", "trailer": "",
        "plot": "A lone young woman searches a harsh world for the baby dragon she raised. Blender Foundation open movie (CC BY).",
        "audio": [("eng", "English", 523, 1)], "subtitles": False,
    },
    {
        "id": 1006, "title": "Tears of Steel", "year": 2012, "ext": "mp4", "category": "13",
        "file": "movies/1006-tears-of-steel.mp4", "seconds": 60, "color": (60, 110, 150),
        "rating": "5.6", "genre": "Sci-Fi, Short", "director": "Ian Hubert",
        "cast": "Derek de Lint, Sergio Hasselbaink, Rogier Schippers, Vanja Rukavina", "country": "Netherlands",
        "release": "2012-09-26", "trailer": "",
        "plot": "Scientists in a ruined Amsterdam try to rewrite a painful memory to stop a robot invasion. "
                "Blender Foundation open movie (CC BY).",
        "audio": [("eng", "English", 587, 1)], "subtitles": False,
    },
    {
        "id": 1007, "title": "Elephants Dream", "year": 2006, "ext": "mp4", "category": "13",
        "file": "movies/1007-elephants-dream.mp4", "seconds": 60, "color": (120, 90, 150),
        "rating": "5.6", "genre": "Animation, Sci-Fi", "director": "Bassam Kurdali",
        "cast": "Tygo Gernandt, Cas Jansen", "country": "Netherlands", "release": "2006-03-24", "trailer": "",
        "plot": "Two men wander an endless, shifting machine and disagree about what it is. "
                "The first Blender Foundation open movie (CC BY).",
        "audio": [("eng", "English", 659, 1)], "subtitles": False,
    },
]

SERIES = [
    {
        "id": 1, "title": "Signal Lost", "year": 2024, "slug": "signal-lost", "category": "20",
        "color": (20, 140, 150), "rating": "8.1", "genre": "Sci-Fi, Mystery", "director": "Ana Log",
        "cast": "Carrier Wave, Dee Modulator, Phase Locke", "release": "2024-03-01",
        "plot": "A broadcast engineer chases a transmission that only appears between keyframes.",
        "seasons": {1: ["Static", "Carrier Wave", "Dead Air"], 2: ["Bandwidth", "Packet Loss", "Reconnect"]},
    },
    {
        "id": 2, "title": "The Test Pattern Bakery", "year": 2022, "slug": "test-pattern-bakery",
        "category": "21", "color": (200, 90, 60), "rating": "7.2", "genre": "Comedy",
        "director": "Pat Isserie", "cast": "Crois Sant, Gamma Gateau, Chroma Key", "release": "2022-09-14",
        "plot": "A small bakery that only sells pastries shaped like broadcast test cards.",
        "seasons": {1: ["Color Bars & Croissants", "Gamma Ray Gateau", "Pixel Pie"],
                    2: ["Chroma Key Lime", "Interlaced Pastry", "Final Frame"]},
    },
]

LIVE_CATEGORIES = [("1", "News"), ("2", "Sports"), ("3", "Entertainment"), ("4", "Empty Category")]
VOD_CATEGORIES = [("10", "Action & Adventure"), ("11", "Drama & Mystery"), ("12", "Documentaries"),
                  ("13", "Open Movies (CC BY)")]
SERIES_CATEGORIES = [("20", "Sci-Fi Series"), ("21", "Comedy Series")]

# Xtream live streams. feed=None is a deliberately dead stream (404) sharing a tvg-id with a working one.
XTREAM_LIVE = [
    {"id": 1, "feed": 1, "name": "Tuner News", "category": "1", "archive": 3},
    {"id": 2, "feed": 2, "name": "Tuner Sports", "category": "2", "archive": 3},
    {"id": 3, "feed": 3, "name": "Tuner Movies", "category": "3", "archive": 0},
    {"id": 4, "feed": 4, "name": "Tuner Kids", "category": "3", "archive": 7},
    {"id": 5, "feed": None, "name": "Tuner Sports 4K", "category": "2", "archive": 0,
     "tvg": "sports.tuner", "logo": "sports"},
]


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def episodes(series: dict) -> list[dict]:
    out = []
    for season, titles in series["seasons"].items():
        for i, title in enumerate(titles, start=1):
            epid = 2000 + series["id"] * 100 + (season - 1) * len(titles) + i
            out.append({
                "id": epid, "season": season, "episode": i, "title": title,
                "file": f"series/{series['slug']}/s{season:02d}e{i:02d}.mp4",
                "image": f"episode/{epid}.png",
                "plot": f"{series['title']} season {season}, episode {i}: \"{title}\". "
                        f"{EPISODE_SECONDS}-second test episode with burned-in S{season:02d}E{i:02d} title.",
            })
    return out


def all_episodes() -> dict[int, tuple[dict, dict]]:
    return {ep["id"]: (s, ep) for s in SERIES for ep in episodes(s)}


def feed_ts_path(n: int) -> Path:
    return MEDIA / "channels" / f"feed{n}-{FEEDS[n]['slug']}.ts"


def feed_hls_dir(n: int) -> Path:
    return MEDIA / "hls" / f"feed{n}"


IMG = {
    "logo": lambda slug: f"logo/{slug}.png",
    "feed_backdrop": lambda slug: f"backdrop/{slug}.png",
    "movie_poster": lambda mid: f"poster/movie-{mid}.png",
    "movie_backdrop": lambda mid: f"backdrop/movie-{mid}.png",
    "series_poster": lambda sid: f"poster/series-{sid}.png",
    "series_backdrop": lambda sid: f"backdrop/series-{sid}.png",
}

# --------------------------------------------------------------------------------------------------
# MPEG-TS handling: scanning, loop rewriting (PTS/DTS/PCR + continuity counters)
# --------------------------------------------------------------------------------------------------

TS_PACKET = 188
PTS_WRAP = 1 << 33


class MediaMissing(Exception):
    pass


def _read_pts(b, o: int) -> int:
    return (((b[o] >> 1) & 0x07) << 30) | (b[o + 1] << 22) | ((b[o + 2] >> 1) << 15) | (b[o + 3] << 7) | (b[o + 4] >> 1)


def _write_pts(b: bytearray, o: int, v: int) -> None:
    b[o] = (b[o] & 0xF0) | ((v >> 29) & 0x0E) | 0x01
    b[o + 1] = (v >> 22) & 0xFF
    b[o + 2] = ((v >> 14) & 0xFE) | 0x01
    b[o + 3] = (v >> 7) & 0xFF
    b[o + 4] = ((v << 1) & 0xFE) | 0x01


def _read_pcr27(b, o: int) -> int:
    base = (b[o] << 25) | (b[o + 1] << 17) | (b[o + 2] << 9) | (b[o + 3] << 1) | (b[o + 4] >> 7)
    ext = ((b[o + 4] & 0x01) << 8) | b[o + 5]
    return base * 300 + ext


class TSBuffer:
    """An MPEG-TS file in memory plus the byte offsets needed to re-time it cheaply."""

    def __init__(self, data: bytes, label: str):
        n = len(data) // TS_PACKET
        if n == 0 or data[0] != 0x47:
            raise ValueError(f"{label}: not an MPEG-TS file")
        d = data if len(data) == n * TS_PACKET else data[: n * TS_PACKET]
        self.label = label
        self.data = d
        self.n = n
        self.cc_offsets = array("L")
        self.cc_pids = array("H")
        self.pcr_offsets = array("L")
        self.pts_offsets = array("L")
        self.payload_counts: dict[int, int] = {}
        self.pkt_time = array("d", [0.0]) * n     # seconds since the first PCR (step function)
        self.keyframes: list[int] = []
        self.pats: list[int] = []
        video_starts: list[int] = []
        pts_by_stream: dict[int, list[int]] = {}
        first_pcr = None
        t = 0.0
        for i in range(n):
            o = i * TS_PACKET
            if d[o] != 0x47:
                raise ValueError(f"{label}: lost sync at packet {i}")
            b1 = d[o + 1]
            pid = ((b1 & 0x1F) << 8) | d[o + 2]
            afc = (d[o + 3] >> 4) & 3
            p = o + 4
            rai = False
            if afc & 2:
                alen = d[o + 4]
                if alen:
                    flags = d[o + 5]
                    rai = bool(flags & 0x40)
                    if flags & 0x10 and alen >= 7:
                        pcr = _read_pcr27(d, o + 6)
                        if first_pcr is None:
                            first_pcr = pcr
                        t = (pcr - first_pcr) / 27_000_000
                        self.pcr_offsets.append(o + 6)
                p = o + 5 + alen
            self.pkt_time[i] = t
            if not afc & 1:
                continue
            self.cc_offsets.append(o + 3)
            self.cc_pids.append(pid)
            self.payload_counts[pid] = self.payload_counts.get(pid, 0) + 1
            if not b1 & 0x40:
                continue
            if pid == 0:
                self.pats.append(i)
                continue
            end = o + TS_PACKET
            if p + 14 <= end and d[p] == 0 and d[p + 1] == 0 and d[p + 2] == 1:
                sid = d[p + 3]
                if sid == 0xBD or 0xC0 <= sid <= 0xEF:
                    flags2 = d[p + 7] >> 6
                    if flags2 & 2:
                        self.pts_offsets.append(p + 9)
                        if flags2 == 3 and p + 19 <= end:
                            self.pts_offsets.append(p + 14)
                        pts_by_stream.setdefault(sid, []).append(_read_pts(d, p + 9))
                        if sid >= 0xE0:
                            video_starts.append(i)
                            if rai:
                                self.keyframes.append(i)
        if not self.keyframes:
            self.keyframes = video_starts or [0]
        self.kf_times = [self.pkt_time[i] for i in self.keyframes]
        # Per elementary stream: (first PTS, last PTS, frame duration) in 90 kHz ticks.
        self.spans: dict[int, tuple[int, int, int]] = {}
        for sid, values in pts_by_stream.items():
            uniq = sorted(set(values))
            diffs = [b - a for a, b in zip(uniq, uniq[1:])]
            self.spans[sid] = (uniq[0], uniq[-1], min(diffs) if diffs else 0)

    def shifted(self, shift90: int, cc_add: dict[int, int]) -> bytes:
        """Copy with every PTS/DTS/PCR moved by ``shift90`` (90 kHz) and continuity counters advanced."""
        cc_add = {pid: v % 16 for pid, v in cc_add.items() if v % 16}
        shift90 %= PTS_WRAP
        if not shift90 and not cc_add:
            return self.data
        b = bytearray(self.data)
        if cc_add:
            for off, pid in zip(self.cc_offsets, self.cc_pids):
                add = cc_add.get(pid)
                if add:
                    v = b[off]
                    b[off] = (v & 0xF0) | ((v + add) & 0x0F)
        if shift90:
            for off in self.pcr_offsets:
                base = (b[off] << 25) | (b[off + 1] << 17) | (b[off + 2] << 9) | (b[off + 3] << 1) | (b[off + 4] >> 7)
                base = (base + shift90) % PTS_WRAP
                b[off] = (base >> 25) & 0xFF
                b[off + 1] = (base >> 17) & 0xFF
                b[off + 2] = (base >> 9) & 0xFF
                b[off + 3] = (base >> 1) & 0xFF
                b[off + 4] = ((base & 1) << 7) | (b[off + 4] & 0x7F)
            for off in self.pts_offsets:
                _write_pts(b, off, (_read_pts(b, off) + shift90) % PTS_WRAP)
        return bytes(b)


def loop_period90(buffers: list[TSBuffer]) -> int:
    """Loop length in 90 kHz ticks: video span (first..last PTS) plus one frame duration.

    Video carries one frame per PES, so its frame duration is exact; audio PES packets bundle several
    AAC frames, so audio is only used when there is no video. make_media.sh trims looping clips so
    their audio (including the AAC priming frame) ends exactly where the video does.
    """
    sids = {sid for b in buffers for sid in b.spans}
    video = [sid for sid in sids if sid >= 0xE0]
    period = 0
    for sid in video or sids:
        spans = [b.spans[sid] for b in buffers if sid in b.spans]
        frames = [f for _, _, f in spans if f]
        period = max(period, max(hi for _, hi, _ in spans) - min(lo for lo, _, _ in spans) + (min(frames) if frames else 0))
    if not period:
        raise ValueError("no timestamps found in " + ", ".join(b.label for b in buffers))
    return period


class LiveFeed:
    """A channel clip looped forever on a virtual timeline that starts at ANCHOR."""

    def __init__(self, n: int):
        path = feed_ts_path(n)
        if not path.is_file():
            raise MediaMissing(f"missing {path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}")
        self.n = n
        self.ts = TSBuffer(path.read_bytes(), path.name)
        self.period90 = loop_period90([self.ts])
        self.period = self.period90 / 90000
        self.loop_size = self.ts.n * TS_PACKET

    def loop_bytes(self, loop: int) -> bytes:
        return _feed_loop(self.n, loop)

    def build_loop(self, loop: int) -> bytes:
        return self.ts.shifted(loop * self.period90, {pid: loop * c for pid, c in self.ts.payload_counts.items()})

    def join_point(self, vtime: float) -> int:
        """Absolute packet index to start a client at: the PAT before the last keyframe <= vtime."""
        loop = math.floor(vtime / self.period)
        within = vtime - loop * self.period
        k = bisect.bisect_right(self.ts.kf_times, within) - 1
        if k < 0:
            loop -= 1
            k = len(self.ts.keyframes) - 1
        kf = self.ts.keyframes[k]
        j = bisect.bisect_right(self.ts.pats, kf) - 1
        start = self.ts.pats[j] if j >= 0 else kf
        return loop * self.ts.n + start


class HLSFeed:
    """The pre-segmented HLS rendition of a channel, served as an endless live window."""

    def __init__(self, n: int):
        folder = feed_hls_dir(n)
        index = folder / "index.m3u8"
        if not index.is_file():
            raise MediaMissing(f"missing {index}")
        self.n = n
        self.durations: list[float] = []
        names: list[str] = []
        pending = None
        for line in index.read_text().splitlines():
            line = line.strip()
            if line.startswith("#EXTINF:"):
                pending = float(line[8:].split(",")[0])
            elif line and not line.startswith("#") and pending is not None:
                self.durations.append(pending)
                names.append(line)
                pending = None
        if not names:
            raise MediaMissing(f"{index} lists no segments")
        self.segments = [TSBuffer((folder / name).read_bytes(), name) for name in names]
        self.period90 = loop_period90(self.segments)
        self.cc_counts: dict[int, int] = {}
        for s in self.segments:
            for pid, c in s.payload_counts.items():
                self.cc_counts[pid] = self.cc_counts.get(pid, 0) + c
        self.cum = [0.0]
        for d in self.durations:
            self.cum.append(self.cum[-1] + d)
        self.period = self.cum[-1]
        self.count = len(names)
        self.target = max(1, max(int(d + 0.5) for d in self.durations))

    def segment_bytes(self, j: int) -> bytes:
        return _hls_segment(self.n, j)

    def build_segment(self, j: int) -> bytes:
        loop, k = divmod(j, self.count)
        return self.segments[k].shifted(loop * self.period90, {pid: loop * c for pid, c in self.cc_counts.items()})

    def segment_at(self, vtime: float) -> int:
        loop = math.floor(vtime / self.period)
        within = vtime - loop * self.period
        k = min(self.count - 1, max(0, bisect.bisect_right(self.cum, within) - 1))
        return loop * self.count + k

    def segment_start(self, j: int) -> float:
        loop, k = divmod(j, self.count)
        return loop * self.period + self.cum[k]

    def playlist(self, first: int, count: int, *, live: bool, media_sequence: int) -> str:
        lines = ["#EXTM3U", "#EXT-X-VERSION:3", f"#EXT-X-TARGETDURATION:{self.target}"]
        if not live:
            lines.append("#EXT-X-PLAYLIST-TYPE:VOD")
        lines.append(f"#EXT-X-MEDIA-SEQUENCE:{media_sequence}")
        for j in range(first, first + count):
            pdt = dt.datetime.fromtimestamp(ANCHOR + self.segment_start(j), dt.timezone.utc)
            lines.append("#EXT-X-PROGRAM-DATE-TIME:" + pdt.isoformat(timespec="milliseconds").replace("+00:00", "Z"))
            lines.append(f"#EXTINF:{self.durations[j % self.count]:.3f},")
            lines.append(f"/hlsseg/{self.n}/{j}.ts")
        if not live:
            lines.append("#EXT-X-ENDLIST")
        return "\n".join(lines) + "\n"


_registry_lock = threading.Lock()
_registry: dict[tuple[str, int], object] = {}


def live_feed(n: int) -> LiveFeed:
    with _registry_lock:
        key = ("ts", n)
        if key not in _registry:
            _registry[key] = LiveFeed(n)
        return _registry[key]  # type: ignore[return-value]


def hls_feed(n: int) -> HLSFeed:
    with _registry_lock:
        key = ("hls", n)
        if key not in _registry:
            _registry[key] = HLSFeed(n)
        return _registry[key]  # type: ignore[return-value]


@functools.lru_cache(maxsize=8)
def _feed_loop(n: int, loop: int) -> bytes:
    return live_feed(n).build_loop(loop)


@functools.lru_cache(maxsize=96)
def _hls_segment(n: int, j: int) -> bytes:
    return hls_feed(n).build_segment(j)


# --------------------------------------------------------------------------------------------------
# Logging
# --------------------------------------------------------------------------------------------------

_log_lock = threading.Lock()
_active_streams = 0
_active_lock = threading.Lock()


def log(line: str) -> None:
    with _log_lock:
        print(f"{time.strftime('%H:%M:%S')}  {line}", flush=True)


def fmt_bytes(n: int) -> str:
    return f"{n / 1_048_576:.1f}MB" if n >= 1_048_576 else f"{n / 1024:.0f}KB"


def fmt_utc(epoch: float) -> str:
    return dt.datetime.fromtimestamp(epoch, dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def local_tz_name() -> str:
    if os.environ.get("TZ"):
        return os.environ["TZ"]
    real = os.path.realpath("/etc/localtime")
    if "zoneinfo/" in real:
        return real.split("zoneinfo/", 1)[1]
    return time.tzname[0]


# --------------------------------------------------------------------------------------------------
# EPG (XMLTV) — deterministic per (channel, UTC day) so repeated downloads agree
# --------------------------------------------------------------------------------------------------

EPG_CHANNELS = [
    # (tvg-id, display name, extra display names, image slug)
    ("news.tuner", "Tuner News", ["Tuner News HD"], "news"),
    ("sports.tuner", "Tuner Sports", ["Tuner Sports 4K"], "sports"),
    ("movies.tuner", "Tuner Movies", [], "movies"),
    ("kids.tuner", "Tuner Kids", [], "kids"),
    ("weather.tuner", "Tuner Weather", [], None),   # guide-only channel: no stream carries it
]

EPG_SHOWS = {
    "news.tuner": {
        "titles": ["Morning Briefing", "World Report", "Business Today", "Tech Desk", "Weather Watch",
                   "Headlines at the Hour", "Q&A: Ask the <Experts>", "Evening News", "Late Edition",
                   "Politics Live"],
        "subtitles": ["Markets open higher", "Election special", "Interview: the keyframe whisperer",
                      "Storm season outlook", "Packets around the world"],
        "categories": ["News", "Current Affairs"], "rating": "TV-G",
    },
    "sports.tuner": {
        "titles": ["Matchday Live", "Goal Rush", "Tennis Highlights", "Motorsport Weekly", "The Locker Room",
                   "Basketball Tonight", "Golf Classics", "Sports Centre"],
        "subtitles": ["Semi-final", "Qualifying", "Round 12", "Season review", "Final, part 2"],
        "categories": ["Sports", "Football"], "rating": "TV-PG",
    },
    "movies.tuner": {
        "titles": ["Feature Presentation", "Classic Cinema", "Director's Cut", "Midnight Movie", "Matinee",
                   "Behind the Scenes", "Short Film Showcase"],
        "subtitles": ["Big Buck Test (2021)", "The Multitrack Mystery (2023)", "Matroska Nights (2019)",
                      "A Codec Romance", "Return of the Bitrate"],
        "categories": ["Movie", "Drama"], "rating": "TV-14",
    },
    "kids.tuner": {
        "titles": ["Cartoon Carousel", "Science Squad", "Alphabet Adventures", "Puppet Theatre",
                   "Dino Discovery", "Story Time", "Build It!"],
        "subtitles": ["The Big Balloon", "Volcano Day", "Letters A to F", "The Lost Sock", "Rainbow Bridge"],
        "categories": ["Children", "Animation"], "rating": "TV-Y",
    },
    "weather.tuner": {
        "titles": ["Weather Now", "Weekend Forecast", "Storm Tracker"],
        "subtitles": ["Coastal update", "Pollen report", "Long-range outlook"],
        "categories": ["Weather"], "rating": "TV-G",
    },
}

FLAVOR = [
    "Generated by the Tuner test kit.",
    "Contains scenes of mild colour bars.",
    "Times are relative to the server clock.",
    "Repeat of an earlier broadcast.",
    "Live coverage with expert analysis.",
]


def _day_slots(tvg: str, day: int) -> list[tuple[int, int]]:
    rng = random.Random(f"{tvg}/{day}")
    t, end, out = day, day + 86400, []
    while t < end:
        remaining = (end - t) // 60
        minutes = rng.choice((30, 30, 45, 60, 60))
        if remaining <= 60:
            minutes = remaining
        elif remaining - minutes < 30:
            minutes = remaining - 30
        out.append((t, t + minutes * 60))
        t += minutes * 60
    return out


def programmes(tvg: str, lo: float, hi: float, base: str, slug: str | None, channel_name: str) -> list[dict]:
    show = EPG_SHOWS[tvg]
    out = []
    day = int(lo // 86400) * 86400
    while day < hi:
        for start, stop in _day_slots(tvg, day):
            if stop <= lo or start >= hi:
                continue
            rng = random.Random(f"{tvg}@{start}")
            title = rng.choice(show["titles"])
            minutes = (stop - start) // 60
            hhmm = lambda e: time.strftime("%H:%M", time.gmtime(e))  # noqa: E731
            prog = {
                "start": start, "stop": stop, "title": title,
                "subtitle": rng.choice(show["subtitles"]) if rng.random() < 0.7 else None,
                "desc": f"{title} on {channel_name}. Airs {hhmm(start)}-{hhmm(stop)} UTC ({minutes} min). "
                        f"{rng.choice(FLAVOR)}",
                "categories": show["categories"],
                "icon": f"{base}/img/{IMG['feed_backdrop'](slug)}" if slug and rng.random() < 0.35 else None,
                "season": rng.randint(1, 6), "episode": rng.randint(1, 24),
                "with_episode": tvg in ("kids.tuner", "sports.tuner", "news.tuner") and rng.random() < 0.6,
                "new": rng.random() < 0.25,
                "rating": show["rating"],
                "credits": tvg == "movies.tuner",
            }
            out.append(prog)
        day += 86400
    return out


def xmltv(base: str) -> bytes:
    now = time.time()
    lo, hi = now - 12 * 3600, now + 36 * 3600
    stamp = lambda e: time.strftime("%Y%m%d%H%M%S +0000", time.gmtime(e))  # noqa: E731
    attr = lambda v: escape(v, {'"': "&quot;"})  # noqa: E731
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<!DOCTYPE tv SYSTEM "xmltv.dtd">',
           f'<!-- Tuner test kit guide, generated {fmt_utc(now)}; window now-12h .. now+36h -->',
           '<tv generator-info-name="Tuner Test Kit" source-info-name="local">']
    for tvg, name, extra, slug in EPG_CHANNELS:
        out.append(f'  <channel id="{attr(tvg)}">')
        for display in [name, *extra]:
            out.append(f'    <display-name lang="en">{escape(display)}</display-name>')
        if slug:
            out.append(f'    <icon src="{attr(base)}/img/{IMG["logo"](slug)}"/>')
        out.append("  </channel>")
    for tvg, name, _, slug in EPG_CHANNELS:
        for p in programmes(tvg, lo, hi, base, slug, name):
            out.append(f'  <programme start="{stamp(p["start"])}" stop="{stamp(p["stop"])}" channel="{attr(tvg)}">')
            out.append(f'    <title lang="en">{escape(p["title"])}</title>')
            if p["subtitle"]:
                out.append(f'    <sub-title lang="en">{escape(p["subtitle"])}</sub-title>')
            out.append(f'    <desc lang="en">{escape(p["desc"])}</desc>')
            if p["credits"]:
                out.append("    <credits><director>Rhea Tester</director><actor>Bun E. Rabbit</actor>"
                           "<actor>Stereo Jones</actor></credits>")
            for c in p["categories"]:
                out.append(f'    <category lang="en">{escape(c)}</category>')
            if p["icon"]:
                out.append(f'    <icon src="{attr(p["icon"])}"/>')
            if p["with_episode"]:
                out.append(f'    <episode-num system="xmltv_ns">{p["season"] - 1}.{p["episode"] - 1}.0/1</episode-num>')
                out.append(f'    <episode-num system="onscreen">S{p["season"]:02d}E{p["episode"]:02d}</episode-num>')
            if p["new"]:
                out.append("    <new/>")
            else:
                out.append("    <previously-shown/>")
            out.append(f'    <rating system="VCHIP"><value>{p["rating"]}</value></rating>')
            out.append("  </programme>")
    out.append("</tv>")
    return ("\n".join(out) + "\n").encode("utf-8")


# --------------------------------------------------------------------------------------------------
# Playlists
# --------------------------------------------------------------------------------------------------

CATCHUP_ATTRS = [("catchup", "append"), ("catchup-source", "?utc={utc}&lutc={lutc}"), ("catchup-days", "3")]


def _extinf(attrs: list[tuple[str, str]], title: str) -> str:
    return "#EXTINF:-1 " + " ".join(f'{k}="{v}"' for k, v in attrs) + "," + title


def m3u_playlist(base: str) -> str:
    def logo(slug):
        return f"{base}/img/{IMG['logo'](slug)}"

    lines = [f'#EXTM3U url-tvg="{base}/epg.xml.gz"']

    def chan(tvg, tvg_name, logo_url, chno, group, title, url, extra=(), vlcopts=()):
        attrs = [("tvg-id", tvg), ("tvg-name", tvg_name), ("tvg-logo", logo_url), ("tvg-chno", str(chno)),
                 ("group-title", group), *extra]
        lines.append(_extinf(attrs, title))
        lines.extend(f"#EXTVLCOPT:{o}" for o in vlcopts)
        lines.append(url)

    # News: raw TS + catchup, an HLS backup with the same tvg-id, and a stream that stalls (watchdog test)
    chan("news.tuner", "Tuner News", logo("news"), 101, "News", "Tuner News", f"{base}/stream/1.ts", CATCHUP_ATTRS)
    chan("news.tuner", "Tuner News HD", logo("news"), 102, "News", "Tuner News (Backup HLS)", f"{base}/stream/1.m3u8")
    chan("news.tuner", "Tuner News Flaky", f"{base}/img/logo/missing.png", 103, "News",
         "Tuner News (Flaky - stalls after 20s)", f"{base}/flaky/1.ts")
    # Sports: live HLS + catchup, and a dead (404) duplicate to exercise failover
    chan("sports.tuner", "Tuner Sports", logo("sports"), 201, "Sports", "Tuner Sports", f"{base}/stream/2.m3u8",
         CATCHUP_ATTRS)
    chan("sports.tuner", "Tuner Sports 4K", logo("sports"), 202, "Sports", "Tuner Sports 4K (Dead - 404)",
         f"{base}/dead/2.ts")
    # Entertainment: a User-Agent locked TS channel, and kids TS + catchup (tvg-name contains a comma)
    chan("movies.tuner", "Tuner Movies", logo("movies"), 301, "Entertainment", "Tuner Movies (UA locked)",
         f"{base}/ua/3.ts", vlcopts=[f"http-user-agent={LOCKED_UA}", f"http-referrer={LOCKED_REFERRER}"])
    chan("kids.tuner", "Tuner Kids, Family & Fun", logo("kids"), 302, "Entertainment", "Tuner Kids",
         f"{base}/stream/4.ts", CATCHUP_ATTRS)

    # A few Xtream-style VOD lines; Tuner routes /movie/ and /series/ URLs into the VOD library.
    for m in (MOVIES[0], MOVIES[2]):
        lines.append(_extinf([("tvg-id", ""), ("tvg-name", f"{m['title']} ({m['year']})"),
                              ("tvg-logo", f"{base}/img/{IMG['movie_poster'](m['id'])}"),
                              ("group-title", "Movies")], f"{m['title']} ({m['year']})"))
        lines.append(f"{base}/movie/{USERNAME}/{PASSWORD}/{m['id']}.{m['ext']}")
    s = SERIES[0]
    for ep in episodes(s)[:3]:
        name = f"{s['title']} S{ep['season']:02d} E{ep['episode']:02d} {ep['title']}"
        lines.append(_extinf([("tvg-id", ""), ("tvg-name", name),
                              ("tvg-logo", f"{base}/img/{IMG['series_poster'](s['id'])}"),
                              ("group-title", "Series")], name))
        lines.append(f"{base}/series/{USERNAME}/{PASSWORD}/{ep['id']}.mp4")
    return "\n".join(lines) + "\n"


def xtream_m3u(base: str, plus: bool, output: str) -> str:
    ext = "m3u8" if output in ("m3u8", "hls") else "ts"
    cats = dict(LIVE_CATEGORIES)
    lines = [f'#EXTM3U url-tvg="{base}/xmltv.php?username={USERNAME}&password={PASSWORD}"' if plus else "#EXTM3U"]

    def add(attrs, title, url):
        lines.append(_extinf(attrs, title) if plus else f"#EXTINF:-1,{title}")
        lines.append(url)

    for s in XTREAM_LIVE:
        tvg, slug = _live_tvg_logo(s)
        attrs = [("tvg-id", tvg), ("tvg-name", s["name"]), ("tvg-logo", f"{base}/img/{IMG['logo'](slug)}"),
                 ("group-title", cats[s["category"]])]
        if s["archive"]:
            attrs.append(("tvg-rec", str(s["archive"])))
        add(attrs, s["name"], f"{base}/live/{USERNAME}/{PASSWORD}/{s['id']}.{ext}")
    vcats = dict(VOD_CATEGORIES)
    for m in MOVIES:
        name = f"{m['title']} ({m['year']})"
        add([("tvg-id", ""), ("tvg-name", name), ("tvg-logo", f"{base}/img/{IMG['movie_poster'](m['id'])}"),
             ("group-title", vcats[m["category"]])], name, f"{base}/movie/{USERNAME}/{PASSWORD}/{m['id']}.{m['ext']}")
    scats = dict(SERIES_CATEGORIES)
    for s in SERIES:
        for ep in episodes(s):
            name = f"{s['title']} S{ep['season']:02d} E{ep['episode']:02d}"
            add([("tvg-id", ""), ("tvg-name", name), ("tvg-logo", f"{base}/img/{IMG['series_poster'](s['id'])}"),
                 ("group-title", scats[s["category"]])], name, f"{base}/series/{USERNAME}/{PASSWORD}/{ep['id']}.mp4")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------------------------------
# Xtream Codes API
# --------------------------------------------------------------------------------------------------

ADDED_BASE = 1_727_740_800  # 2024-10-01, "added" timestamps are spread after this


def _live_tvg_logo(s: dict) -> tuple[str, str]:
    if s["feed"]:
        f = FEEDS[s["feed"]]
        return f["tvg"], f["slug"]
    return s["tvg"], s["logo"]


def xtream_login(host: str, port: str) -> dict:
    now = int(time.time())
    with _active_lock:
        active = _active_streams
    return {
        "user_info": {
            "username": USERNAME, "password": PASSWORD, "message": "Tuner Test Kit - local Xtream emulator",
            "auth": 1, "status": "Active", "exp_date": str(now + 30 * 86400), "is_trial": "0",
            "active_cons": str(active), "created_at": str(now - 200 * 86400), "max_connections": "2",
            "allowed_output_formats": ["m3u8", "ts", "rtmp"],
        },
        "server_info": {
            "xui": True, "version": "1.5.12", "revision": 2, "url": host, "port": port, "https_port": "8443",
            "server_protocol": "http", "rtmp_port": "8880", "timezone": local_tz_name(),
            "timestamp_now": now, "time_now": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(now)),
            "process": True,
        },
    }


def xtream_live_streams(base: str, category: str | None) -> list[dict]:
    out = []
    for i, s in enumerate(XTREAM_LIVE):
        if category and s["category"] != category:
            continue
        tvg, slug = _live_tvg_logo(s)
        item = {
            "num": i + 1, "name": s["name"], "stream_type": "live", "stream_id": s["id"],
            "stream_icon": f"{base}/img/{IMG['logo'](slug)}", "epg_channel_id": tvg,
            "added": str(ADDED_BASE + s["id"] * 3600), "is_adult": "0" if s["id"] % 2 else 0,
            "category_id": s["category"], "category_ids": [int(s["category"])], "custom_sid": "",
            "tv_archive": 1 if s["archive"] else 0, "direct_source": "", "thumbnail": "",
        }
        # Quirk: archive duration is a string on some streams and a number on others.
        item["tv_archive_duration"] = (str(s["archive"]) if s["id"] % 2 else s["archive"]) if s["archive"] else 0
        out.append(item)
    return out


def xtream_vod_streams(base: str, category: str | None) -> list[dict]:
    out = []
    for i, m in enumerate(MOVIES):
        if category and m["category"] != category:
            continue
        item = {
            "num": i + 1, "name": f"{m['title']} ({m['year']})", "stream_type": "movie", "stream_id": m["id"],
            "stream_icon": f"{base}/img/{IMG['movie_poster'](m['id'])}", "rating": m["rating"],
            "rating_5based": round(float(m["rating"]) / 2, 1), "added": str(ADDED_BASE + m["id"] * 60),
            "is_adult": "0", "category_id": m["category"], "category_ids": [int(m["category"])],
            "container_extension": m["ext"], "custom_sid": "", "direct_source": "", "tmdb": "",
        }
        if i == 0:
            item["year"] = str(m["year"])  # newer panels add a separate year field
        out.append(item)
    return out


def xtream_vod_info(base: str, vod_id: str) -> dict:
    m = next((m for m in MOVIES if str(m["id"]) == vod_id), None)
    if not m:
        return {"info": [], "movie_data": []}   # what real panels return for unknown ids
    secs = m["seconds"]
    return {
        "info": {
            "kinopoisk_url": "", "tmdb_id": "", "name": m["title"], "o_name": m["title"],
            "cover_big": f"{base}/img/{IMG['movie_poster'](m['id'])}",
            "movie_image": f"{base}/img/{IMG['movie_poster'](m['id'])}",
            "releasedate": m["release"], "episode_run_time": "", "youtube_trailer": m["trailer"],
            "director": m["director"], "actors": m["cast"], "cast": m["cast"], "description": m["plot"],
            "plot": m["plot"], "age": "", "mpaa_rating": "", "rating_count_kinopoisk": 0, "country": m["country"],
            "genre": m["genre"], "backdrop_path": [f"{base}/img/{IMG['movie_backdrop'](m['id'])}"],
            "duration_secs": secs, "duration": time.strftime("%H:%M:%S", time.gmtime(secs)),
            "video": {"codec_name": "h264", "width": 1280, "height": 720},
            "audio": {"codec_name": "aac", "channels": 2}, "bitrate": 1100, "rating": m["rating"],
        },
        "movie_data": {
            "stream_id": m["id"], "name": f"{m['title']} ({m['year']})", "added": str(ADDED_BASE + m["id"] * 60),
            "category_id": m["category"], "category_ids": [int(m["category"])],
            "container_extension": m["ext"], "custom_sid": "", "direct_source": "",
        },
    }


def _series_info_block(base: str, s: dict) -> dict:
    return {
        "name": f"{s['title']} ({s['year']})", "cover": f"{base}/img/{IMG['series_poster'](s['id'])}",
        "plot": s["plot"], "cast": s["cast"], "director": s["director"], "genre": s["genre"],
        "releaseDate": s["release"], "release_date": s["release"],
        "last_modified": str(ADDED_BASE + s["id"] * 86400), "rating": s["rating"],
        "rating_5based": round(float(s["rating"]) / 2, 1),
        "backdrop_path": [f"{base}/img/{IMG['series_backdrop'](s['id'])}"],
        "youtube_trailer": "", "episode_run_time": str(EPISODE_SECONDS // 60 or 1), "category_id": s["category"],
        "category_ids": [int(s["category"])],
    }


def xtream_series(base: str, category: str | None) -> list[dict]:
    out = []
    for i, s in enumerate(SERIES):
        if category and s["category"] != category:
            continue
        out.append({"num": i + 1, "series_id": s["id"], **_series_info_block(base, s)})
    return out


def xtream_series_info(base: str, series_id: str) -> dict:
    s = next((s for s in SERIES if str(s["id"]) == series_id), None)
    if not s:
        return {"seasons": [], "info": [], "episodes": []}
    by_season: dict[int, list[dict]] = {}
    for ep in episodes(s):
        by_season.setdefault(ep["season"], []).append({
            "id": str(ep["id"]),
            # Quirk: series 1 sends episode_num as a string, series 2 as a number.
            "episode_num": str(ep["episode"]) if s["id"] == 1 else ep["episode"],
            "title": f"{s['title']} - S{ep['season']:02d}E{ep['episode']:02d} - {ep['title']}",
            "container_extension": "mp4",
            "info": {
                "tmdb_id": "", "releasedate": s["release"], "plot": ep["plot"], "duration_secs": EPISODE_SECONDS,
                "duration": time.strftime("%H:%M:%S", time.gmtime(EPISODE_SECONDS)),
                "movie_image": f"{base}/img/{ep['image']}", "bitrate": 600, "rating": s["rating"],
                "season": str(ep["season"]),
            },
            "custom_sid": "", "added": str(ADDED_BASE + ep["id"] * 60), "season": ep["season"], "direct_source": "",
        })
    seasons = [{
        "air_date": s["release"], "episode_count": len(eps), "id": s["id"] * 10 + n, "name": f"Season {n}",
        "overview": f"Season {n} of {s['title']}.", "season_number": n,
        "cover": f"{base}/img/{IMG['series_poster'](s['id'])}",
        "cover_big": f"{base}/img/{IMG['series_poster'](s['id'])}",
    } for n, eps in sorted(by_season.items())]
    # Quirk: series 1 uses the usual {"1": [...]} map; series 2 the list-of-lists some panels send.
    eps_json: object = ({str(n): eps for n, eps in sorted(by_season.items())} if s["id"] == 1
                        else [eps for _, eps in sorted(by_season.items())])
    return {"seasons": seasons, "info": _series_info_block(base, s), "episodes": eps_json}


def xtream_short_epg(base: str, stream_id: str, limit: int) -> dict:
    s = next((s for s in XTREAM_LIVE if str(s["id"]) == stream_id), None)
    if not s:
        return {"epg_listings": []}
    tvg, slug = _live_tvg_logo(s)
    name = next(n for t, n, _, _ in EPG_CHANNELS if t == tvg)
    now = time.time()
    progs = [p for p in programmes(tvg, now - 3600, now + 12 * 3600, base, slug, name) if p["stop"] > now][:limit]
    b64 = lambda t: base64.b64encode(t.encode()).decode()  # noqa: E731
    fmt = lambda e: time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(e))  # noqa: E731
    return {"epg_listings": [{
        "id": str(p["start"]), "epg_id": "1", "title": b64(p["title"]), "lang": "en",
        "start": fmt(p["start"]), "end": fmt(p["stop"]), "description": b64(p["desc"]), "channel_id": tvg,
        "start_timestamp": str(p["start"]), "stop_timestamp": str(p["stop"]),
        "now_playing": 1 if p["start"] <= now < p["stop"] else 0, "has_archive": 0,
    } for p in progs]}


# --------------------------------------------------------------------------------------------------
# HTTP
# --------------------------------------------------------------------------------------------------

CONTENT_TYPES = {
    ".ts": "video/mp2t", ".m3u8": "application/vnd.apple.mpegurl", ".mp4": "video/mp4",
    ".mkv": "video/x-matroska", ".png": "image/png", ".jpg": "image/jpeg", ".srt": "application/x-subrip",
    ".xml": "application/xml", ".gz": "application/gzip", ".m3u": "audio/x-mpegurl",
}
CLIENT_GONE = (BrokenPipeError, ConnectionResetError, ConnectionAbortedError, TimeoutError)


def parse_range(header: str, size: int):
    """Returns (start, end) for a single satisfiable byte range, None to ignore, or 'invalid' (416)."""
    m = re.fullmatch(r"\s*bytes\s*=\s*(\d*)\s*-\s*(\d*)\s*(,.*)?", header)
    if not m or (m.group(1) == "" and m.group(2) == ""):
        return None
    first, last = m.group(1), m.group(2)
    if first == "":
        length = int(last)
        if length == 0:
            return "invalid"
        return max(0, size - length), size - 1
    start = int(first)
    end = min(int(last), size - 1) if last else size - 1
    if start >= size or start > end:
        return "invalid"
    return start, end


def check_creds(user: str | None, password: str | None) -> bool:
    return user == USERNAME and password == PASSWORD


def parse_timeshift_start(text: str) -> float | None:
    """`YYYY-MM-DD:HH-MM` (Xtream timeshift) in server-local time -> epoch."""
    m = re.fullmatch(r"(\d{4})-(\d{2})-(\d{2})[:_ ](\d{2})[-:](\d{2})(?:[-:](\d{2}))?", text)
    if not m:
        return None
    y, mo, d, h, mi, s = (int(g) if g else 0 for g in m.groups())
    return time.mktime((y, mo, d, h, mi, s, 0, 0, -1))


class Handler(BaseHTTPRequestHandler):
    server_version = "TunerTestKit/1.0"

    def version_string(self):
        return self.server_version
    protocol_version = "HTTP/1.1"
    timeout = 120

    # -- plumbing ---------------------------------------------------------------------------------

    def log_message(self, format, *args):  # noqa: A002 - silence the default access log
        pass

    def log_request(self, code="-", size="-"):
        pass

    def do_GET(self):
        self._dispatch(head=False)

    def do_HEAD(self):
        self._dispatch(head=True)

    def _dispatch(self, head: bool):
        self.is_head = head
        self.headers_out = False
        split = urllib.parse.urlsplit(self.path)
        self.route_path = urllib.parse.unquote(split.path)
        self.query = dict(urllib.parse.parse_qsl(split.query, keep_blank_values=True))
        try:
            route(self)
        except CLIENT_GONE:
            self.close_connection = True
        except MediaMissing as e:
            if not self.headers_out:
                self.send_text(503, f"Test media not generated ({e}). Run scripts/testkit/make_media.sh first.\n")
            else:
                self.close_connection = True
        except Exception:  # noqa: BLE001
            traceback.print_exc()
            self.close_connection = True
            if not self.headers_out:
                try:
                    self.send_text(500, "internal error\n")
                except Exception:  # noqa: BLE001
                    pass

    def end_headers(self):
        self.headers_out = True
        super().end_headers()

    @property
    def host_port(self) -> tuple[str, str]:
        host = self.headers.get("Host", "")
        m = re.fullmatch(r"([A-Za-z0-9.\-]+|\[[0-9A-Fa-f:.]+\])(?::(\d{1,5}))?", host)
        if m:
            return m.group(1), m.group(2) or "80"
        h = CONFIG["host"] if CONFIG["host"] not in ("0.0.0.0", "::", "") else "127.0.0.1"
        return h, str(CONFIG["port"])

    @property
    def base(self) -> str:
        host, port = self.host_port
        return f"http://{host}" + ("" if port == "80" else f":{port}")

    def log(self, status: int, note: str = "") -> None:
        ua = self.headers.get("User-Agent", "-")
        ua = ua if len(ua) <= 48 else ua[:45] + "..."
        method = "HEAD" if self.is_head else "GET "
        rng = self.headers.get("Range")
        extra = f" [{note}]" if note else ""
        extra += f" Range:{rng.replace('bytes=', '')}" if rng and status in (200, 206, 416) else ""
        log(f"{status} {method} {self.path}{extra}  UA={ua}")

    # -- responses --------------------------------------------------------------------------------

    def respond(self, status: int, body: bytes, ctype: str, headers=(), note: str = ""):
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        for k, v in headers:
            self.send_header(k, v)
        self.end_headers()
        self.log(status, note)
        if not self.is_head:
            self.wfile.write(body)

    def send_text(self, status: int, text: str, note: str = ""):
        self.respond(status, text.encode(), "text/plain; charset=utf-8", note=note or text.strip().split("\n")[0][:80])

    def send_json(self, obj, note: str = ""):
        # PHP's json_encode escapes slashes and non-ASCII; mimic it.
        body = json.dumps(obj, ensure_ascii=True, separators=(",", ":")).replace("/", "\\/").encode()
        self.respond(200, body, "application/json; charset=utf-8", note=note)

    def send_ranged(self, size: int, reader, ctype: str, note: str = "", headers=()):
        status, start, end = 200, 0, size - 1
        header = self.headers.get("Range")
        if header and size > 0:
            r = parse_range(header, size)
            if r == "invalid":
                self.send_response(416)
                self.send_header("Content-Range", f"bytes */{size}")
                self.send_header("Content-Length", "0")
                self.end_headers()
                self.log(416, note)
                return
            if r:
                status, (start, end) = 206, r
        length = max(0, end - start + 1)
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(length))
        self.send_header("Accept-Ranges", "bytes")
        if status == 206:
            self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
        for k, v in headers:
            self.send_header(k, v)
        self.end_headers()
        self.log(status, note)
        if self.is_head or length == 0:
            return
        for chunk in reader(start, length):
            self.wfile.write(chunk)

    def send_file(self, path: Path, note: str = ""):
        if not path.is_file():
            if not MEDIA.is_dir():
                raise MediaMissing(f"{MEDIA} does not exist")
            return self.send_text(404, f"not found: {path.name}\n")
        size = path.stat().st_size
        ctype = CONTENT_TYPES.get(path.suffix.lower(), "application/octet-stream")

        def reader(start, length):
            with path.open("rb") as f:
                f.seek(start)
                while length > 0:
                    chunk = f.read(min(262_144, length))
                    if not chunk:
                        break
                    length -= len(chunk)
                    yield chunk

        mtime = time.strftime("%a, %d %b %Y %H:%M:%S GMT", time.gmtime(path.stat().st_mtime))
        self.send_ranged(size, reader, ctype, note, headers=[("Last-Modified", mtime)])

    def send_bytes_ranged(self, data: bytes, ctype: str, note: str = "", headers=()):
        view = memoryview(data)
        self.send_ranged(len(data), lambda s, n: (view[s:s + n],), ctype, note, headers)

    # -- live / archive streaming -----------------------------------------------------------------

    def stream_live_ts(self, n: int, label: str, stall_after: float | None = None):
        global _active_streams
        feed = live_feed(n)
        ts = feed.ts
        abs_i = feed.join_point(time.time() - ANCHOR)
        self.send_response(200)
        self.send_header("Content-Type", "video/mp2t")
        self.send_header("Cache-Control", "no-cache, no-store")
        self.send_header("Connection", "close")
        self.end_headers()
        self.close_connection = True
        loop0, idx0 = divmod(abs_i, ts.n)
        behind = (time.time() - ANCHOR) - (loop0 * feed.period + ts.pkt_time[idx0])
        self.log(200, f"{label} feed={n} live-ts join={behind:.1f}s behind live, loop {loop0}"
                      + (f", will stall after {stall_after:.0f}s" if stall_after else ""))
        if self.is_head:
            return
        t0, sent, reason = time.time(), 0, "client closed"
        with _active_lock:
            _active_streams += 1
        try:
            while True:
                now = time.time()
                if stall_after is not None and now - t0 >= stall_after:
                    log(f"... STALL {self.path}: stopped sending after {now - t0:.0f}s (socket kept open 60s)")
                    time.sleep(60)
                    reason = "stall finished"
                    break
                loop, idx = divmod(abs_i, ts.n)
                rel = (now - ANCHOR + LIVE_LEAD) - loop * feed.period
                end = min(bisect.bisect_right(ts.pkt_time, rel), idx + 2000)
                if end <= idx:
                    time.sleep(0.03)
                    continue
                data = feed.loop_bytes(loop)
                self.wfile.write(memoryview(data)[idx * TS_PACKET:end * TS_PACKET])
                sent += (end - idx) * TS_PACKET
                abs_i += end - idx
        except CLIENT_GONE:
            pass
        finally:
            with _active_lock:
                _active_streams -= 1
            log(f"END {self.path}: {time.time() - t0:.1f}s, {fmt_bytes(sent)} ({reason})")

    def serve_archive(self, n: int, ext: str, start: float, seconds: float, label: str):
        seconds = max(60.0, min(float(seconds), ARCHIVE_MAX))
        what = (f"{label} feed={n} archive start={fmt_utc(start)} "
                f"(server-local {time.strftime('%Y-%m-%d %H:%M', time.localtime(start))}) dur={seconds / 60:.0f}min")
        if ext == "m3u8":
            hf = hls_feed(n)
            first = hf.segment_at(start - ANCHOR)
            count = max(1, math.ceil(seconds / (hf.period / hf.count)))
            body = hf.playlist(first, count, live=False, media_sequence=0).encode()
            return self.respond(200, body, CONTENT_TYPES[".m3u8"], [("Cache-Control", "no-cache")], note=what + " vod-hls")
        feed = live_feed(n)
        abs0 = feed.join_point(start - ANCHOR)
        packets = math.ceil(seconds / feed.period * feed.ts.n)
        size = packets * TS_PACKET
        first_byte = abs0 * TS_PACKET

        def reader(pos, length):
            absolute = first_byte + pos
            while length > 0:
                loop, off = divmod(absolute, feed.loop_size)
                take = min(length, feed.loop_size - off)
                yield memoryview(feed.loop_bytes(loop))[off:off + take]
                absolute += take
                length -= take

        self.send_ranged(size, reader, "video/mp2t", note=what + f" {fmt_bytes(size)}")

    def serve_feed(self, n: int, ext: str, label: str, flaky: bool = False):
        if n not in FEEDS:
            return self.send_text(404, f"no such channel {n}\n")
        utc = self.query.get("utc") or self.query.get("start")
        if utc and re.fullmatch(r"\d+(\.\d+)?", utc):
            start, now = float(utc), time.time()
            if start < now - 30:
                lutc = self.query.get("lutc") or self.query.get("end")
                end = float(lutc) if lutc and re.fullmatch(r"\d+(\.\d+)?", lutc) else now
                return self.serve_archive(n, ext, start, end - start, label)
        if ext == "m3u8":
            hf = hls_feed(n)
            last = hf.segment_at(time.time() - ANCHOR) - 1     # newest *complete* segment
            first = last - HLS_WINDOW + 1
            body = hf.playlist(first, HLS_WINDOW, live=True, media_sequence=first).encode()
            return self.respond(200, body, CONTENT_TYPES[".m3u8"], [("Cache-Control", "no-cache")],
                                note=f"{label} feed={n} live-hls seq={first}")
        return self.stream_live_ts(n, label, stall_after=float(self.query.get("after", FLAKY_STALL_AFTER)) if flaky else None)


class TestKitServer(ThreadingHTTPServer):
    daemon_threads = True

    def handle_error(self, request, client_address):
        # Clients (players, ffprobe) routinely drop keep-alive or streaming sockets; don't dump tracebacks.
        if isinstance(sys.exc_info()[1], CLIENT_GONE + (ConnectionError,)):
            return
        super().handle_error(request, client_address)


# --------------------------------------------------------------------------------------------------
# Routing
# --------------------------------------------------------------------------------------------------

R_STREAM = re.compile(r"/(stream|ua|flaky)/(\d+)\.(ts|m3u8)")
R_HLSSEG = re.compile(r"/hlsseg/(\d+)/(-?\d+)\.ts")
R_HLSVOD = re.compile(r"/hls/(\d+)/([\w.\-]+)")
R_LIVE = re.compile(r"/live/([^/]+)/([^/]+)/(\d+)(?:\.(\w+))?")
R_MOVIE = re.compile(r"/movie/([^/]+)/([^/]+)/(\d+)(?:\.(\w+))?")
R_SERIES = re.compile(r"/series/([^/]+)/([^/]+)/(\d+)(?:\.(\w+))?")
R_TIMESHIFT = re.compile(r"/timeshift/([^/]+)/([^/]+)/(\d+)/([^/]+)/(\d+)\.(ts|m3u8)")
R_SHORT_LIVE = re.compile(r"/([^/]+)/([^/]+)/(\d+)(?:\.(ts|m3u8))?")
R_IMG = re.compile(r"/img/(.+)")


def route(h: Handler) -> None:  # noqa: C901 - a flat routing table reads best here
    p, q, base = h.route_path, h.query, h.base

    if p in ("/", "/index.html"):
        return h.send_text(200, index_page(base), note="index")
    if p == "/playlist.m3u":
        return h.respond(200, m3u_playlist(base).encode(), CONTENT_TYPES[".m3u"], note="m3u playlist")
    if p == "/epg.xml":
        return h.respond(200, xmltv(base), "application/xml; charset=utf-8", note="xmltv")
    if p == "/epg.xml.gz":
        return h.respond(200, gzip.compress(xmltv(base), mtime=0), CONTENT_TYPES[".gz"], note="xmltv gz")
    if p.startswith("/dead/"):
        return h.send_text(404, "Stream not found (deliberately dead test channel)\n")

    if m := R_STREAM.fullmatch(p):
        kind, n, ext = m.group(1), int(m.group(2)), m.group(3)
        if kind == "ua":
            ua = h.headers.get("User-Agent", "")
            ref = h.headers.get("Referer", "")
            ref_note = "referer ok" if ref == LOCKED_REFERRER else f"referer {'missing' if not ref else 'WRONG: ' + ref}"
            if LOCKED_UA_TOKEN not in ua:
                return h.send_text(403, f"Forbidden: User-Agent must contain '{LOCKED_UA_TOKEN}' ({ref_note})\n")
            return h.serve_feed(n, ext, f"ua-locked: UA ok, {ref_note};")
        return h.serve_feed(n, ext, kind, flaky=(kind == "flaky"))

    if m := R_HLSSEG.fullmatch(p):
        n, j = int(m.group(1)), int(m.group(2))
        if n not in FEEDS:
            return h.send_text(404, "no such channel\n")
        return h.send_bytes_ranged(hls_feed(n).segment_bytes(j), "video/mp2t", note=f"feed={n} seg={j}")
    if m := R_HLSVOD.fullmatch(p):
        n = int(m.group(1))
        if n not in FEEDS:
            return h.send_text(404, "no such channel\n")
        return h.send_file(feed_hls_dir(n) / m.group(2), note="static hls")
    if m := R_IMG.fullmatch(p):
        img_root = (MEDIA / "img").resolve()
        target = (img_root / m.group(1)).resolve()
        if not target.is_relative_to(img_root):
            return h.send_text(404, "not found\n")
        return h.send_file(target)

    # ---- Xtream Codes ----
    if p == "/player_api.php":
        if not check_creds(q.get("username"), q.get("password")):
            return h.send_json({"user_info": {"auth": 0}}, note="AUTH FAILED")
        action = q.get("action", "")
        cat = q.get("category_id") or None
        if action == "":
            host, port = h.host_port
            data = xtream_login(host.strip("[]"), port)
        elif action == "get_live_categories":
            data = [{"category_id": c, "category_name": n, "parent_id": 0} for c, n in LIVE_CATEGORIES]
        elif action == "get_live_streams":
            data = xtream_live_streams(base, cat)
        elif action == "get_vod_categories":
            data = [{"category_id": c, "category_name": n, "parent_id": 0} for c, n in VOD_CATEGORIES]
        elif action == "get_vod_streams":
            data = xtream_vod_streams(base, cat)
        elif action == "get_vod_info":
            data = xtream_vod_info(base, q.get("vod_id", ""))
        elif action == "get_series_categories":
            data = [{"category_id": c, "category_name": n, "parent_id": 0} for c, n in SERIES_CATEGORIES]
        elif action == "get_series":
            data = xtream_series(base, cat)
        elif action == "get_series_info":
            data = xtream_series_info(base, q.get("series_id", ""))
        elif action in ("get_short_epg", "get_simple_data_table"):
            limit = q.get("limit", "")
            data = xtream_short_epg(base, q.get("stream_id", ""),
                                    int(limit) if limit.isdigit() else (4 if action == "get_short_epg" else 50))
        else:
            data = []
        return h.send_json(data, note=f"xtream {action or 'login'}")
    if p == "/xmltv.php":
        if not check_creds(q.get("username"), q.get("password")):
            return h.send_text(401, "Unauthorized\n")
        return h.respond(200, xmltv(base), "application/xml; charset=utf-8", note="xtream xmltv")
    if p == "/get.php":
        if not check_creds(q.get("username"), q.get("password")):
            return h.send_text(401, "Unauthorized\n")
        kind = q.get("type", "m3u_plus")
        body = xtream_m3u(base, plus=(kind != "m3u"), output=q.get("output", "ts")).encode()
        return h.respond(200, body, CONTENT_TYPES[".m3u"],
                         [("Content-Disposition", 'attachment; filename="playlist.m3u"')], note=f"xtream {kind}")
    if p == "/streaming/timeshift.php":
        if not check_creds(q.get("username"), q.get("password")):
            return h.send_text(401, "Unauthorized\n")
        return serve_timeshift(h, q.get("stream", ""), q.get("start", ""), q.get("duration", "60"), "ts")
    if m := R_LIVE.fullmatch(p):
        return serve_xtream_live(h, *m.groups())
    if m := R_MOVIE.fullmatch(p):
        user, pw, vid, ext = m.groups()
        if not check_creds(user, pw):
            return h.send_text(401, "Unauthorized\n")
        movie = next((x for x in MOVIES if str(x["id"]) == vid), None)
        if not movie:
            return h.send_text(404, f"no such movie {vid}\n")
        note = f"movie {movie['title']}" + (f" (asked .{ext}, serving .{movie['ext']})" if ext and ext != movie["ext"] else "")
        return h.send_file(MEDIA / movie["file"], note=note)
    if m := R_SERIES.fullmatch(p):
        user, pw, eid, ext = m.groups()
        if not check_creds(user, pw):
            return h.send_text(401, "Unauthorized\n")
        found = all_episodes().get(int(eid))
        if not found:
            return h.send_text(404, f"no such episode {eid}\n")
        s, ep = found
        return h.send_file(MEDIA / ep["file"], note=f"episode {s['title']} S{ep['season']:02d}E{ep['episode']:02d}")
    if m := R_TIMESHIFT.fullmatch(p):
        user, pw, minutes, start, sid, ext = m.groups()
        if not check_creds(user, pw):
            return h.send_text(401, "Unauthorized\n")
        return serve_timeshift(h, sid, start, minutes, ext)
    if (m := R_SHORT_LIVE.fullmatch(p)) and check_creds(m.group(1), m.group(2)):
        return serve_xtream_live(h, *m.groups())
    return h.send_text(404, f"not found: {p}\n")


def serve_xtream_live(h: Handler, user: str, pw: str, sid: str, ext: str | None) -> None:
    if not check_creds(user, pw):
        return h.send_text(401, "Unauthorized\n")
    s = next((s for s in XTREAM_LIVE if str(s["id"]) == sid), None)
    if not s:
        return h.send_text(404, f"no such stream {sid}\n")
    if not s["feed"]:
        return h.send_text(404, f"Stream not found (stream {sid} is deliberately dead)\n")
    ext = (ext or "ts").lower()
    if ext not in ("ts", "m3u8"):
        return h.send_text(404, f"unsupported live format .{ext}\n")
    return h.serve_feed(s["feed"], ext, f"xtream live {s['id']}")


def serve_timeshift(h: Handler, sid: str, start_text: str, minutes: str, ext: str) -> None:
    s = next((s for s in XTREAM_LIVE if str(s["id"]) == sid), None)
    if not s or not s["feed"]:
        return h.send_text(404, f"no archive for stream {sid}\n")
    start = parse_timeshift_start(start_text)
    if start is None:
        return h.send_text(400, f"bad timeshift start '{start_text}' (want YYYY-MM-DD:HH-MM, server-local)\n")
    try:
        mins = max(1, int(minutes))
    except ValueError:
        return h.send_text(400, f"bad duration '{minutes}'\n")
    return h.serve_archive(s["feed"], ext, start, mins * 60, f"xtream timeshift {sid}")


def index_page(base: str) -> str:
    return f"""Tuner test kit — local IPTV provider
====================================
Media folder: {MEDIA}
Server-local timezone: {local_tz_name()}  (Xtream time_now / timeshift use this)

M3U source
  Playlist  {base}/playlist.m3u
  EPG       {base}/epg.xml.gz   ({base}/epg.xml uncompressed)

Xtream Codes source
  Server    {base}
  Username  {USERNAME}
  Password  {PASSWORD}
  API       {base}/player_api.php?username={USERNAME}&password={PASSWORD}[&action=...]
  M3U       {base}/get.php?username={USERNAME}&password={PASSWORD}&type=m3u_plus&output=ts
  XMLTV     {base}/xmltv.php?username={USERNAME}&password={PASSWORD}

Channels (feed n = burned-in name)
  /stream/n.ts     endless pseudo-live MPEG-TS (wall-clock synced)    n = 1 news, 2 sports, 3 movies, 4 kids
  /stream/n.m3u8   live HLS sliding window ({HLS_WINDOW} x 2 s segments)
  /stream/n.ts?utc=EPOCH&lutc=EPOCH   catchup (finite, seekable); same for .m3u8 (VOD playlist)
  /ua/n.ts         requires a User-Agent containing '{LOCKED_UA_TOKEN}' (403 otherwise)
  /flaky/n.ts      stops sending after {FLAKY_STALL_AFTER:.0f}s but keeps the socket open (?after=SECONDS)
  /dead/...        always 404
  /hls/n/index.m3u8  the static VOD HLS rendition
"""


# --------------------------------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------------------------------

def preload() -> None:
    for n in FEEDS:
        try:
            t0 = time.time()
            f, hf = live_feed(n), hls_feed(n)
            _feed_loop(n, math.floor((time.time() - ANCHOR) / f.period))
            log(f"feed {n} ({FEEDS[n]['name']}): ts {fmt_bytes(f.loop_size)}, loop {f.period:.2f}s, "
                f"{len(f.ts.keyframes)} keyframes; hls {hf.count} segs / {hf.period:.2f}s "
                f"(scanned in {time.time() - t0:.1f}s)")
        except MediaMissing as e:
            log(f"feed {n}: media missing ({e}) — run scripts/testkit/make_media.sh")
        except Exception as e:  # noqa: BLE001
            log(f"feed {n}: failed to load: {e}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Tuner local IPTV test server")
    ap.add_argument("port", nargs="?", type=int, default=int(os.environ.get("TESTKIT_PORT", DEFAULT_PORT)))
    ap.add_argument("--host", default=os.environ.get("TESTKIT_HOST", DEFAULT_HOST))
    args = ap.parse_args()
    CONFIG.update(host=args.host, port=args.port)

    server = TestKitServer((args.host, args.port), Handler)
    shown = args.host if args.host not in ("0.0.0.0", "::") else "127.0.0.1"
    base = f"http://{shown}:{args.port}"
    print(index_page(base), flush=True)
    if not MEDIA.is_dir():
        print(f"WARNING: {MEDIA} not found — run scripts/testkit/make_media.sh first.\n", flush=True)
    threading.Thread(target=preload, daemon=True).start()
    log(f"listening on {base}  (Ctrl-C to stop)")
    try:
        server.serve_forever(poll_interval=0.5)
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
        log("stopped")


if __name__ == "__main__":
    main()
